
export const PRODUCT_TYPES = [
    'Hardware',
    'Software',
    'Cloud',
    'Hybrid',
    'Service',
    'AI Tool',
    'Platform',
    'Content & Licensing',
    'Data & Analytics',
] as const;

export type ProductType = typeof PRODUCT_TYPES[number];

// Main categories available for each product type.
export const MAIN_CATEGORIES_BY_TYPE: Record<ProductType, string[]> = {
    Hardware: [
        'Capture & Acquisition',
        'Audio Production & Radio',
        'Displays & Monitoring',
        'Broadcast Graphics & Vision Mixing',
        'Infrastructure & Transmission',
        'Intercom & Communication Systems',
        'Satellite & RF Equipment',
        'Physical Storage Systems',
    ],
    Software: [
        'Post-Production & Editing',
        'Live Production & Broadcast Control',
        'Newsroom & Editorial Systems',
        'Management & Orchestration',
        'Graphics, Branding & Motion Design',
        'Analytics & Audience Intelligence',
        'Security, DRM & Content Protection',
        'Monetization & Ad Tech',
    ],
    Cloud: [
        'Cloud Production & Collaboration',
        'OTT & Streaming Platform Services',
        'Live Streaming & Contribution',
        'Video Encoding & Transcoding',
        'Storage & Active Archive',
        'Intelligent Tech & Cognitive Services',
        'Cloud Playout & Virtual Distribution',
        'Content Delivery & CDN',
    ],
    Hybrid: [
        'Hybrid Remote Production',
        'Hybrid Broadcast & OTT Delivery',
        'Hybrid Storage & Compute',
        'Edge Video Processing',
    ],
    Service: [
        'Production Facilities & Rental',
        'Live Event Production Services',
        'Post-Production & Finishing Services',
        'Managed Broadcast & Playout Services',
        'Integration & Engineering Services',
        'Content Strategy & Creative Services',
        'Media Monitoring & PR Services',
        'Localization & Accessibility Services',
        'Professional Training & Consultancy',
    ],
    'AI Tool': [
        'AI Video Generation',
        'AI Image Generation',
        'AI Audio & Music',
        'AI Voice & Speech',
        'AI Editing & Post-Production',
        'AI Avatar & Presenter',
        'AI Writing & Scripting',
        'AI Content Moderation & Safety',
        'AI Metadata, Search & Discovery',
        'AI Analytics & Recommendations',
    ],
    Platform: [
        'Streaming & OTT Platforms',
        'Social Video & Creator Platforms',
        'Content Management & Publishing',
        'Podcast & Audio Platforms',
        'Newsroom & Editorial Platforms',
        'Sports & Live Event Platforms',
        'E-Learning & Training Platforms',
        'Creator Monetization Platforms',
    ],
    'Content & Licensing': [
        'Stock Footage & B-Roll',
        'Royalty-Free Music & Sound Effects',
        'Motion Graphics & Templates',
        'Stock Photography & Images',
        'News Wire & Agency Content',
        'Documentary & Archive Footage',
    ],
    'Data & Analytics': [
        'Audience Measurement & Ratings',
        'Streaming & Viewership Analytics',
        'Social Media & Digital Analytics',
        'Media Monitoring & Sentiment',
        'Ad Performance & Attribution',
        'Competitive Intelligence',
    ],
};

// Flat list of every main category (each is unique to a single product type).
export const MAIN_CATEGORIES = Object.values(MAIN_CATEGORIES_BY_TYPE).flat() as readonly string[];

export function getProductTypeForMainCategory(mainCategory?: string | null): ProductType | undefined {
    if (!mainCategory) return undefined;

    return PRODUCT_TYPES.find((type) =>
        MAIN_CATEGORIES_BY_TYPE[type].includes(mainCategory)
    );
}

// Sub categories keyed by main category.
export const SUB_CATEGORIES: Record<string, string[]> = {

    // ─── HARDWARE ────────────────────────────────────────────────────────────

    'Capture & Acquisition': [
        'Studio & Broadcast Cameras',
        'Cinema & Digital Film Cameras',
        'Camcorders & ENG / EFP Units',
        'Action Cameras & POV Cameras',
        '360° & VR / XR Cameras',
        'PTZ & Robotic Camera Systems',
        'Drones & Aerial Camera Systems',
        'Broadcast Lenses & Cinema Lenses',
        'Camera Support, Tripods & Gimbals',
        'Prompters & Teleprompters',
        'Lighting, Grip & Rigging Systems',
        'Green Screen & Cyclorama Systems',
    ],
    'Audio Production & Radio': [
        'Broadcast Mixing Consoles',
        'Audio Processors & Equalizers',
        'Microphones & Transducers',
        'Headphones & Headsets',
        'Audio Monitors & Reference Speakers',
        'Radio Transmitters & Exciters',
        'AM / FM / DAB Broadcast Equipment',
        'On-Air Audio Processors & Loudness',
        'IFB, Talkback & Intercom Audio',
        'Wireless Microphone Systems',
        'Recording & Playback Devices',
    ],
    'Displays & Monitoring': [
        'Broadcast Reference Monitors',
        'Waveform Monitors & Vectorscopes',
        'Production & Field Monitors',
        'Video Walls & Large-Format Displays',
        'SDR / HDR / HDR10+ / Dolby Vision Displays',
        'Multiviewers & Mosaic Processors',
        'Confidence Monitors & Prompter Screens',
    ],
    'Broadcast Graphics & Vision Mixing': [
        'Vision Mixers & Production Switchers',
        'Hardware Character Generators (CG)',
        'Clip Servers & Playout Appliances',
        'Live Replay & Slow-Motion Systems',
        'Virtual Set & XR Stage Hardware',
        'Stinger & Transition Effect Processors',
    ],
    'Infrastructure & Transmission': [
        'Signal Converters & Distribution Amps',
        'Routers & SDI / IP Video Matrices',
        'IP Gateway & ST 2110 Infrastructure',
        'Video Sync Generators & SPGs',
        'Transmitters, Antennas & RF Systems',
        'OB Trucks, Flypacks & Mobile Units',
        'Satellite Uplink & DSNG Vehicles',
        'Fiber Optic & Cabling Systems',
        'Rack Systems & Power Management',
        'KVM & Control Systems',
    ],
    'Intercom & Communication Systems': [
        'Wired Party-Line Intercom',
        'Digital Matrix Intercom',
        'Wireless Beltpacks & Base Stations',
        'IP-Based & Cloud Intercom',
        'IFB & Talent Monitoring Systems',
        'Talkback & Commentary Systems',
    ],
    'Satellite & RF Equipment': [
        'Satellite Uplink & Downlink Terminals',
        'DTH & DSNG Systems',
        'DVB & ATSC Modulators',
        'RF Distribution & Combiners',
        'Spectrum Analyzers & RF Test Equipment',
        'Satellite News Gathering (SNG) Kits',
    ],
    'Physical Storage Systems': [
        'On-Premises NAS / SAN Arrays',
        'SSD & NVMe Media Arrays',
        'HDD RAID Storage Systems',
        'LTO Tape Libraries & Drives',
        'Portable SSD & Media Shuttle Drives',
    ],

    // ─── SOFTWARE ────────────────────────────────────────────────────────────

    'Post-Production & Editing': [
        'Non-Linear Editors (NLE)',
        'Audio DAWs & Processing Tools',
        'Color Grading & Color Management',
        'Visual Effects (VFX) & Compositing',
        'Motion Graphics & Animation Tools',
        '3D, CGI & Rendering Software',
        'Audio Noise Reduction & Restoration',
        'Loudness Normalization & QC Tools',
        'Subtitling & Closed Caption Tools',
        'Proxy Workflow & Transcoding Software',
    ],
    'Live Production & Broadcast Control': [
        'Software Vision Mixers & Switchers',
        'Live Graphics & CG Platforms',
        'Live Replay & Sports Production Software',
        'Live Encoding & Streaming Software',
        'Prompter & Autocue Software',
        'Remote Production & REMI Tools',
        'Virtual Set & Augmented Reality (AR) Software',
        'Esports & Gaming Production Tools',
    ],
    'Newsroom & Editorial Systems': [
        'Newsroom Computer Systems (NRCS)',
        'Digital Asset Management for News',
        'News Wire & Feed Aggregators',
        'Sports Data & Statistics Graphics',
        'Script & Rundown Management',
        'News Analytics & Audience Tools',
    ],
    'Management & Orchestration': [
        'Media Asset Management (MAM)',
        'Production Asset Management (PAM)',
        'Digital Asset Management (DAM)',
        'Playout Automation & Broadcast Servers',
        'Traffic, Scheduling & Rights Management',
        'Workflow Automation & Orchestration Engines',
        'Project Management for Media',
        'Resource Booking & Scheduling Tools',
    ],
    'Graphics, Branding & Motion Design': [
        'Broadcast Graphics Systems',
        'Motion Graphics & Template Engines',
        'Real-Time 3D & AR Graphics',
        'Lower Thirds & Ticker Systems',
        'Branding & Style Guide Tools',
        'Social Media Graphics & Clip Tools',
        'Sport & Data Visualization',
    ],
    'Analytics & Audience Intelligence': [
        'Viewership & Ratings Analytics',
        'Streaming & VOD Analytics',
        'Social Media Analytics',
        'Ad Performance & Attribution Tools',
        'Audience Segmentation & Profiling',
        'Content Performance & Recommendation',
        'QoE / QoS Monitoring Software',
    ],
    'Security, DRM & Content Protection': [
        'Digital Rights Management (DRM)',
        'Watermarking & Forensic Marking',
        'Content Encryption & Packaging',
        'Anti-Piracy & Takedown Monitoring',
        'Secure Video Players & SDKs',
        'Cyber Security for Broadcast',
    ],
    'Monetization & Ad Tech': [
        'Ad Servers & Campaign Management',
        'Dynamic Ad Insertion (DAI / SSAI)',
        'Programmatic Advertising Platforms',
        'Subscription & Paywall Management',
        'Content Rights & Contract Software',
        'Sponsorship & Brand Integration Tools',
        'Revenue Analytics & Reporting',
    ],

    // ─── CLOUD ───────────────────────────────────────────────────────────────

    'Cloud Production & Collaboration': [
        'Cloud-Native Video Editors',
        'Collaborative Review & Approval Platforms',
        'Cloud Multiviewers & Remote Monitoring',
        'Remote Contribution & Communications',
        'Cloud-Based Production Switchers',
        'Virtual Production Environments',
        'Frame.io, Wipster & Review Alternatives',
    ],
    'OTT & Streaming Platform Services': [
        'White-Label OTT Platform Providers',
        'FAST Channel Platforms',
        'Video-on-Demand (VOD) Infrastructure',
        'Subscription Video (SVOD) Platforms',
        'AVOD & TVOD Platform Services',
        'Multi-DRM & Secure Streaming Services',
        'HLS / DASH Packaging & Delivery',
    ],
    'Live Streaming & Contribution': [
        'Cloud Live Production Platforms',
        'Live Stream Management & Multistream',
        'IP Bonded Contribution Services',
        'SRT / RIST Transmission Services',
        'Virtual Events & Webcast Platforms',
        'Stadium & Venue Streaming Services',
        'Contribution & Backhaul Services',
    ],
    'Video Encoding & Transcoding': [
        'Cloud Transcoding & Media Processing',
        'Adaptive Bitrate (ABR) Encoding',
        'GPU-Accelerated Encoding Services',
        'HDR / Dolby Vision Processing',
        'Audio Encoding & AC-3 / Dolby Atmos',
        'Thumbnail & Preview Generation',
        'Automated QC & Compliance Services',
    ],
    'Storage & Active Archive': [
        'Production Cloud Storage',
        'Object Storage (S3-Compatible)',
        'Hot / Warm / Cold Media Tiering',
        'Cloud-Native Archiving Platforms',
        'Media Backup, DR & Sync',
        'Nearline & Deep Archive Services',
    ],
    'Intelligent Tech & Cognitive Services': [
        'Automated Transcription & Captions',
        'AI Translation & Virtual Dubbing',
        'Automated Scene Detection & Indexing',
        'Metadata Auto-Tagging & Enrichment',
        'Content Moderation & Safety Filtering',
        'AI-Driven Highlight & Clip Generation',
        'Facial Recognition & Person Tracking',
    ],
    'Cloud Playout & Virtual Distribution': [
        'Cloud Playout & Channel-in-a-Box',
        'FAST Channel Orchestration',
        'Virtual CDNs & Edge Networks',
        'Cloud Origination & Playback Services',
        'Syndication & Affiliate Distribution',
        'Linear to OTT Channel Conversion',
    ],
    'Content Delivery & CDN': [
        'Premium CDN Providers',
        'Edge Computing & Micro PoPs',
        'Video-Optimized CDN',
        'Multi-CDN Orchestration',
        'Last-Mile Delivery & Peering',
        'CDN Analytics & Performance Tools',
    ],

    // ─── HYBRID ──────────────────────────────────────────────────────────────

    'Hybrid Remote Production': [
        'Edge Transmission Encoders',
        'Mobile 5G Transmitters & Bonded Cellular',
        'Hybrid REMI & At-Home Production',
        'Low-Latency IP Contribution Encoders',
        'Portable LiveU / Dejero-Style Devices',
    ],
    'Hybrid Broadcast & OTT Delivery': [
        'HbbTV & Hybrid Broadcast Broadband',
        'DTT + Streaming Combo Delivery',
        'IP Simulcast & Broadcast Companion Apps',
        'Addressable TV & Hybrid Ad Insertion',
        'Satellite-to-OTT Gateway Services',
    ],
    'Hybrid Storage & Compute': [
        'Cloud-Integrated NAS',
        'Edge Caching & Content Gateway',
        'Hybrid Render Farms & GPU Clusters',
        'On-Premises + Cloud Archive Tiering',
    ],
    'Edge Video Processing': [
        'Hardware-Accelerated Cloud Gateways',
        'Smart Edge Converters & Transcoders',
        'Real-Time Cropping & Reframing Appliances',
        'Edge AI Inference Devices',
        'Micro-DC & On-Site Compute Pods',
    ],

    // ─── SERVICE ─────────────────────────────────────────────────────────────

    'Production Facilities & Rental': [
        'TV Studio & Cyclorama Hire',
        'Podcast & Radio Studio Hire',
        'Camera, Lens & Accessories Rental',
        'Grip, Lighting & Rigging Rental',
        'OB Truck, Flypack & Mobile Unit Hire',
        'Drone & Aerial Filming Services',
        'Photography Studio Hire',
        'Virtual Production & LED Volume Hire',
    ],
    'Live Event Production Services': [
        'Broadcast & OB Production Services',
        'Concert, Festival & Tour Production',
        'Corporate AV & Event Production',
        'Sports Broadcasting Services',
        'Conference & Summit Production',
        'Hybrid & Virtual Event Production',
        'Esports & Gaming Event Production',
        'Red Carpet & Awards Show Production',
    ],
    'Post-Production & Finishing Services': [
        'Video Editing & Assembly',
        'Color Grading & DI Finishing',
        'Audio Post-Production & Sound Design',
        'Music & Score Production',
        'Visual Effects (VFX) & CGI',
        'Motion Graphics & Animation',
        'Subtitling, Dubbing & Localization',
        'Closed Captioning & Accessibility',
        'Quality Control (QC) & Compliance',
        'Mastering, Delivery & Versioning',
    ],
    'Managed Broadcast & Playout Services': [
        'Managed Channel Playout Services',
        'Linear & FAST Channel Management',
        'Broadcast Managed Services (MSP)',
        'Remote Infrastructure Management',
        'NOC & Technical Operations Center',
        'SLA-Based Support & Monitoring',
        'Disaster Recovery & Failover Services',
    ],
    'Integration & Engineering Services': [
        'Systems Integration & Design',
        'IP Broadcast Infrastructure (SMPTE ST 2110)',
        'AV Wiring, Cabling & Patching',
        'Acoustic Design & Soundproofing',
        'Studio Furniture & Custom Build',
        'Broadcast IT & Network Engineering',
        'Cybersecurity Assessment & Hardening',
        'Legacy System Migration',
        'Commissioning & Acceptance Testing',
    ],
    'Content Strategy & Creative Services': [
        'Brand Identity & Visual Design',
        'Content Strategy & Editorial Planning',
        'Scriptwriting & Story Development',
        'Documentary & Film Production',
        'Social Media Content Production',
        'Podcast & Radio Content Production',
        'Animation & Explainer Video',
        'Commercial & Advertising Production',
        'Influencer & Creator Partnerships',
    ],
    'Media Monitoring & PR Services': [
        'TV & Radio Broadcast Monitoring',
        'Online & Social Media Monitoring',
        'Newspaper & Print Media Monitoring',
        'Media Clipping & Archiving',
        'PR & Reputation Management',
        'Crisis Communications Support',
        'Media List & Distribution Services',
    ],
    'Localization & Accessibility Services': [
        'Subtitling & SDH Captioning',
        'Dubbing & Voice-Over Services',
        'Audio Description & AD Production',
        'Sign Language Video Interpretation',
        'Metadata Translation & Versioning',
        'Localization QC & Compliance',
    ],
    'Professional Training & Consultancy': [
        'Technical & Workflow Consultancy',
        'Operator & Crew Training',
        'IP & SMPTE ST 2110 Training',
        'Cloud & Remote Production Training',
        'Managed SLA & Helpdesk Support',
        'Hardware Repairs & Maintenance',
        'Regulatory & Compliance Consultancy',
        'Media Law & Rights Consultancy',
    ],

    // ─── AI TOOL ─────────────────────────────────────────────────────────────

    'AI Video Generation': [
        'Text-to-Video Generation',
        'Image-to-Video Animation',
        'Video Extension & Outpainting',
        'AI Slow-Motion & Frame Interpolation',
        'AI Upscaling & Resolution Enhancement',
        'Scene & Background Generation',
    ],
    'AI Image Generation': [
        'Text-to-Image Generation',
        'Image Editing & Inpainting',
        'Style Transfer & LoRA Fine-Tuning',
        'AI Photography & Portrait Generation',
        'Product & Commercial Image Generation',
        'Concept Art & Storyboard Generation',
    ],
    'AI Audio & Music': [
        'AI Music Composition & Generation',
        'AI Sound Design & SFX Libraries',
        'Audio Restoration & Noise Removal',
        'AI Stem Separation & Remixing',
        'Music Licensing & Sync AI Tools',
    ],
    'AI Voice & Speech': [
        'Text-to-Speech & Voice Cloning',
        'Real-Time Voice Changers & Modulators',
        'AI Dubbing & Lip-Sync Translation',
        'Automated Transcription & Captions',
        'Voice Enhancement & De-Noise',
        'Speaker Identification & Diarization',
    ],
    'AI Editing & Post-Production': [
        'Automated Video Editing & Assembly',
        'AI Color Grading & LUT Generation',
        'Background Removal & Rotoscoping',
        'AI Subtitling & Auto-Captions',
        'Smart Highlight & Clip Extraction',
        'AI Audio Sync & Alignment',
    ],
    'AI Avatar & Presenter': [
        'AI Talking Head & Lip-Sync Avatars',
        'Virtual Human Presenters',
        'Deepfake & Face Swap Tools',
        'AI News Anchor & Reporter Avatars',
        'Custom Avatar Creator Tools',
    ],
    'AI Writing & Scripting': [
        'Script & Storyboard Generation',
        'AI Copywriting & Ad Copy',
        'News Article & Summary Generation',
        'SEO & Metadata Optimization',
        'Prompt Engineering Platforms',
        'AI Research & Fact-Checking Tools',
    ],
    'AI Content Moderation & Safety': [
        'Automated NSFW & Hate Speech Detection',
        'Brand Safety & Ad Suitability',
        'AI Fact-Checking & Deepfake Detection',
        'Child Safety & CSAM Detection',
        'Piracy & Illegal Content Detection',
        'Compliance & Regulatory Monitoring',
    ],
    'AI Metadata, Search & Discovery': [
        'Automated Metadata Generation & Tagging',
        'AI-Powered Video Search & Retrieval',
        'Face Recognition & Celebrity Tagging',
        'Object, Scene & Action Detection',
        'Transcript-Based Content Search',
        'AI-Driven Content Recommendation',
    ],
    'AI Analytics & Recommendations': [
        'Audience Engagement Prediction',
        'Content Performance Forecasting',
        'Churn Prediction & Retention AI',
        'Personalization & Recommendation Engines',
        'Sentiment Analysis & Social Listening',
        'Programmatic Yield Optimization',
    ],

    // ─── PLATFORM ────────────────────────────────────────────────────────────

    'Streaming & OTT Platforms': [
        'SVOD Subscription Platforms',
        'AVOD & Free Streaming Services',
        'TVOD / Pay-Per-View Platforms',
        'FAST Channel Aggregators',
        'Live TV & Virtual MVPD Platforms',
        'Sports Streaming Platforms',
        'Kids & Family Platforms',
        'White-Label OTT Solutions',
    ],
    'Social Video & Creator Platforms': [
        'Short-Form Video Platforms',
        'Long-Form Video Platforms',
        'Live Streaming & Co-Watch Platforms',
        'Vertical Video & Stories Platforms',
        'Creator Marketplaces',
        'Clip & Highlight Platforms',
        'Community & Fan Club Platforms',
    ],
    'Content Management & Publishing': [
        'Headless CMS for Media',
        'Digital Publishing Platforms',
        'DAM & Content Hub Platforms',
        'Video CMS & Publishing Systems',
        'Multi-Channel Publishing Tools',
        'Web & App Publishing Suites',
    ],
    'Podcast & Audio Platforms': [
        'Podcast Hosting & Distribution',
        'Audio-Only Live Platforms',
        'Radio & Music Streaming Services',
        'Audiobook & Spoken Word Platforms',
        'Podcast Analytics & Monetization',
    ],
    'Newsroom & Editorial Platforms': [
        'Digital News Publishing CMS',
        'Newsroom Collaboration Platforms',
        'Wire Service & Syndication Platforms',
        'Live Blog & Real-Time Reporting Tools',
        'Data Journalism & Infographics Platforms',
    ],
    'Sports & Live Event Platforms': [
        'Sports Rights Management Platforms',
        'Live Scores & Sports Data Platforms',
        'Fantasy Sports & Engagement Platforms',
        'Ticket & Event Commerce Platforms',
        'Esports Tournament Platforms',
        'Live Event Fan Engagement Apps',
    ],
    'E-Learning & Training Platforms': [
        'LMS for Media Professionals',
        'Video-Based Learning Platforms',
        'Certification & Credentialing Platforms',
        'Live Webinar & Virtual Classroom',
        'Corporate Training & Onboarding Platforms',
    ],
    'Creator Monetization Platforms': [
        'Subscription & Membership Platforms',
        'Digital Goods & Download Platforms',
        'NFT & Web3 Creator Platforms',
        'Tipping & Fan Support Platforms',
        'Branded Merchandise Platforms',
        'Licensing & Syndication Marketplaces',
    ],

    // ─── CONTENT & LICENSING ─────────────────────────────────────────────────

    'Stock Footage & B-Roll': [
        'Royalty-Free Stock Footage',
        'Rights-Managed Footage Libraries',
        'HD & 4K B-Roll Collections',
        'News & Archival Footage',
        'Aerial & Drone Footage',
        'Time-Lapse & Slow-Motion Footage',
        'CGI & Motion Background Loops',
    ],
    'Royalty-Free Music & Sound Effects': [
        'Background & Ambient Music',
        'Genre-Specific Music Libraries',
        'Sound Effects (SFX) Libraries',
        'Foley & Field Recordings',
        'Broadcast Safe Music Collections',
        'Sync Licensing Music Platforms',
    ],
    'Motion Graphics & Templates': [
        'Broadcast Lower Thirds & Openers',
        'Social Media Video Templates',
        'Transitions & Effects Packs',
        'Logo Reveals & Sting Animations',
        'HUD & Infographic Templates',
        'After Effects & Premiere Templates',
    ],
    'Stock Photography & Images': [
        'Editorial & News Photography',
        'Commercial & Lifestyle Photography',
        'Aerial & Satellite Imagery',
        'Illustrations & Vector Art',
        'AI-Generated Image Libraries',
    ],
    'News Wire & Agency Content': [
        'Breaking News Text Feeds',
        'Photo Wire Services',
        'Video News Agency Feeds',
        'Data Journalism & Infographics Feeds',
        'Sports Data & Results Feeds',
    ],
    'Documentary & Archive Footage': [
        'Historical Archive Collections',
        'Natural History & Wildlife Libraries',
        'Sports & Cultural Archives',
        'Government & Public Domain Footage',
        'Ethnographic & Anthropological Collections',
    ],

    // ─── DATA & ANALYTICS ────────────────────────────────────────────────────

    'Audience Measurement & Ratings': [
        'TV Audience Measurement Panels',
        'Radio & Audio Audience Measurement',
        'OTT & Streaming Ratings Services',
        'Return Path Data Analytics',
        'Cross-Platform Audience Deduplication',
        'Real-Time Ratings & Live Overnights',
    ],
    'Streaming & Viewership Analytics': [
        'Video Platform & VOD Analytics',
        'FAST & Linear Streaming Analytics',
        'QoE & Rebuffering Analytics',
        'Viewer Journey & Funnel Analytics',
        'Subscriber Churn & Retention Analytics',
        'Content Affinity & Watch-Time Analytics',
    ],
    'Social Media & Digital Analytics': [
        'Social Listening & Trend Analysis',
        'Creator & Influencer Analytics',
        'Digital Campaign Performance',
        'SEO & Search Visibility Analytics',
        'App & Mobile Analytics',
        'Website Traffic & Engagement Analytics',
    ],
    'Media Monitoring & Sentiment': [
        'Brand Mention & Share of Voice',
        'TV & Radio Monitoring Services',
        'Online News & Blog Monitoring',
        'Sentiment & Emotion Analysis',
        'Crisis & Issues Monitoring',
        'Competitive Media Spend Analysis',
    ],
    'Ad Performance & Attribution': [
        'TV & CTV Ad Effectiveness Measurement',
        'Cross-Media Attribution Models',
        'Programmatic & DSP Analytics',
        'Viewability & Fraud Detection',
        'Sponsorship ROI Measurement',
        'Brand Lift & Recall Studies',
    ],
    'Competitive Intelligence': [
        'Content Strategy Intelligence',
        'Competitor Audience Insights',
        'Pricing & Subscription Benchmarking',
        'Market Share & Reach Analysis',
        'Genre & Format Trend Tracking',
        'Rights & Acquisition Intelligence',
    ],
};
